@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false

class Client

class Director {
  + Construct()
}

interface IBuilder <<interface>> {
  + BuildPartA()
  + BuildPartB()
  + GetResult()
}

class ConcreteBuilderA {
}

class ConcreteBuilderB {
}

class Product {
}

Client -right-> Director
Director --> IBuilder : uses >
IBuilder <|.. ConcreteBuilderA
IBuilder <|.. ConcreteBuilderB
ConcreteBuilderA --> Product : builds >
@enduml