@startuml object_diagram

object "sv1 : SinhVien" as SV1 {
    maSV = "23110001"
    hoTen = "Nguyen Van A"
    lop = "23DTH1"
}

object "nv1 : NhanVien" as NV1 {
    maNV = "QL001"
    hoTen = "Tran Thi B"
    vaiTro = "Manager"
}

object "dayA : DayNha" as DA {
    maDay = "DA1"
    tenDay = "Dãy A"
}

object "phong101 : Phong" as P101 {
    maPhong = "P101"
    tenPhong = "Phòng 101"
    maDay = "DA1"
    soNguoiHienTai = 1
}

object "hd1 : HopDong" as HD1 {
    maHD = "HD001"
    maSV = "23110001"
    maPhong = "P101"
    trangThai = "Đang hiệu lực"
}

object "hdon1 : HoaDon" as HDon1 {
    maHDon = "BILL001"
    thang = 3
    nam = 2026
    tongTien = 150000
    trangThaiThanhToan = "Đã thanh toán"
}

DA *-- P101
SV1 -- HD1
P101 -- HD1
NV1 -- HD1
P101 -- HDon1
NV1 -- HDon1

@enduml
