@startuml use_case
left to right direction
skinparam packageStyle rectangle

actor "Nhân Viên Quản Lý" as NV
actor "Admin" as Admin

rectangle "Hệ thống Quản lý Kí túc xá (Admin Only)" {
  usecase "Đăng nhập" as UC1
  usecase "Quản lý Sinh viên" as UC6
  usecase "Quản lý Phòng & Dãy nhà" as UC7
  usecase "Tiếp nhận & Đăng ký lưu trú" as UC8
  usecase "Lập & Quản lý Hợp đồng" as UC9
  usecase "Ghi chỉ số điện nước & Lập hóa đơn" as UC10
  usecase "Quản lý Thu tiền & Hóa đơn" as UC4
  usecase "Thống kê báo cáo" as UC11
  
  usecase "Quản lý Nhân viên" as UC12
  usecase "Cấu hình giá dịch vụ" as UC13
  usecase "Xem nhật ký hệ thống" as UC14
}

NV -- UC1
NV -- UC6
NV -- UC7
NV -- UC8
NV -- UC9
NV -- UC10
NV -- UC4
NV -- UC11

Admin -- UC11
Admin -- UC12
Admin -- UC13
Admin -- UC14

UC12 --|> NV : "is a"
@enduml
